
public class UseCase {
	//Just a basic Idea so far. Gonna work on it a bit more tonight.
 private String Name;
 private String ID;
 private String Description;
 private String Actors; // we could split this up into two different things primary and supporting?
 private String Triggers;
 private String Preconditions;
 private String Primaryflow;
 private String Alternativeflow;
 private String MinimalGuaruntees;
 private String SuccessGuaruntees; 
}
